=== Bellier-Baptiste/ESEO_RailwaySimulateurv2/network-journey-simulator/src/configs/map_config_schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="test" elementFormDefault="qualified">

	<xs:element name="map">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="stations">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="station" maxOccurs="unbounded"
								minOccurs="0">
								<xs:complexType>
									<xs:sequence><!--remove the sequence part -->
										<xs:element name="id" type="xs:int" />
										<xs:element name="name" type="xs:string" />
										<xs:element name="position">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="latitude" type="xs:float" />
													<xs:element name="longitude" type="xs:float" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>

										<xs:element name="lines">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" minOccurs="0"
														name="line">
														<xs:complexType>
															<xs:attribute name="id" type="xs:int"
																use="required" />
															<xs:attribute name="platform"
																type="xs:string" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="lines">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="line" minOccurs="0"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="id" type="xs:int"></xs:element>
										<xs:element name="name" type="xs:string"></xs:element>
										<xs:element name="numberOfTrain" type="xs:int"></xs:element>
										<xs:element name="stations">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="station" minOccurs="0"
														maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="id" type="xs:int"
																use="required" />
															<xs:attribute name="order" type="xs:int"
																use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="events">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded">
							<xs:element name="stationClosed" minOccurs="0"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="idStation"></xs:element>
										<xs:element name="start" type="xs:dateTime"></xs:element>
										<xs:element name="end" type="xs:dateTime"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="lineDelay" minOccurs="0"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="stationIdStart" type="xs:int"></xs:element>
										<xs:element name="stationIdEnd" type="xs:int"></xs:element>
										<xs:element name="delay" type="xs:int"></xs:element>
										<xs:element name="start" type="xs:dateTime"></xs:element>
										<xs:element name="end" type="xs:dateTime"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="areas">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="area" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="id" type="xs:int"/>
										<xs:element name="populationDistribution">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Businessman" type="xs:int"/>
													<xs:element name="Child" type="xs:int"/>
													<xs:element name="Retired" type="xs:int"/>
													<xs:element name="Student" type="xs:int"/>
													<xs:element name="Tourist" type="xs:int"/>
													<xs:element name="Unemployed" type="xs:int"/>
													<xs:element name="Worker" type="xs:int"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Bellier-Baptiste/ESEO_RailwaySimulateurv2/network-journey-simulator/src/configs/map_config_s.xml
<map xsi:noNamespaceSchemaLocation="map_config_schema.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="test">
	<stations>
		<station>
			<id>0</id>
			<name>Agapanthe</name>
			<position>
				<latitude>0</latitude>
				<longitude>0</longitude>
			</position>
			<lines>
				<line id="0" platform=""></line>
			</lines>
		</station>
		<station>
			<id>1</id>
			<name>Bleuet</name>
			<position>
				<latitude>0.04185852159906956</latitude>
				<longitude>0.017968969947381848</longitude>
			</position>
			<lines>
				<line id="1" platform=""></line>
			</lines>
		</station>
		<station>
			<id>2</id>
			<name>Coquelicot</name>
			<position>
				<latitude>0.007071067811865477</latitude>
				<longitude>0.0070710678118654745</longitude>
			</position>
			<lines>
				<line id="0" platform=""></line>
			</lines>
		</station>
		<station>
			<id>3</id>
			<name>Dahlia</name>
			<position>
				<latitude>0.03261972627395669</latitude>
				<longitude>0.021795804271032747</longitude>
			</position>
			<lines>
				<line id="1" platform=""></line>
			</lines>
		</station>
		<station>
			<id>4</id>
			<name>Edelweiss</name>
			<position>
				<latitude>0.014142135623730954</latitude>
				<longitude>0.014142135623730949</longitude>
			</position>
			<lines>
				<line id="0" platform=""></line>
			</lines>
		</station>
		<station>
			<id>5</id>
			<name>Ficaire</name>
			<position>
				<latitude>0.023380930948843824</latitude>
				<longitude>0.017968969947381848</longitude>
			</position>
			<lines>
				<line id="0" platform=""></line>
				<line id="1" platform=""></line>
			</lines>
		</station>
		<station>
			<id>6</id>
			<name>Grebera</name>
			<position>
				<latitude>0.03261972627395669</latitude>
				<longitude>0.021795804271032747</longitude>
			</position>
			<lines>
				<line id="0" platform=""></line>
			</lines>
		</station>
		<station>
			<id>7</id>
			<name>Hortensia</name>
			<position>
				<latitude>0.014142135623730958</latitude>
				<longitude>0.014142135623730947</longitude>
			</position>
			<lines>
				<line id="1" platform=""></line>
			</lines>
		</station>
		<station>
			<id>8</id>
			<name>Iris</name>
			<position>
				<latitude>0.03644656059760759</latitude>
				<longitude>0.031034599596145615</longitude>
			</position>
			<lines>
				<line id="0" platform=""></line>
			</lines>
		</station>
		<station>
			<id>9</id>
			<name>Jasmin</name>
			<position>
				<latitude>0.010315301300080053</latitude>
				<longitude>0.0049033402986180825</longitude>
			</position>
			<lines>
				<line id="1" platform=""></line>
			</lines>
		</station>
	</stations>
	<lines>
		<line>
			<id>0</id>
			<name>Black</name>
			<numberOfTrain>2</numberOfTrain>
			<stations>
				<station id="0" order="0"></station>
				<station id="2" order="1"></station>
				<station id="4" order="2"></station>
				<station id="5" order="3"></station>
				<station id="6" order="4"></station>
				<station id="8" order="5"></station>
			</stations>
		</line>
		<line>
			<id>1</id>
			<name>Cyan</name>
			<numberOfTrain>2</numberOfTrain>
			<stations>
				<station id="1" order="0"></station>
				<station id="3" order="1"></station>
				<station id="5" order="2"></station>
				<station id="7" order="3"></station>
				<station id="9" order="4"></station>
			</stations>
		</line>
	</lines>

	<events>
	</events>
</map>
